// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudieAssistenten.Server.Data;

#nullable disable

namespace StudieAssistenten.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("StudieAssistenten.Shared.Models.Flashcard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("GeneratedContentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedContentId");

                    b.ToTable("Flashcards");
                });

            modelBuilder.Entity("StudieAssistenten.Shared.Models.GeneratedContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessingType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudyDocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudyDocumentId");

                    b.HasIndex("TestId");

                    b.ToTable("GeneratedContents");
                });

            modelBuilder.Entity("StudieAssistenten.Shared.Models.StudyDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalFilePath")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TestId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("StudyDocuments");
                });

            modelBuilder.Entity("StudieAssistenten.Shared.Models.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructions")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("StudieAssistenten.Shared.Models.Flashcard", b =>
                {
                    b.HasOne("StudieAssistenten.Shared.Models.GeneratedContent", null)
                        .WithMany("Flashcards")
                        .HasForeignKey("GeneratedContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudieAssistenten.Shared.Models.GeneratedContent", b =>
                {
                    b.HasOne("StudieAssistenten.Shared.Models.StudyDocument", "StudyDocument")
                        .WithMany("GeneratedContents")
                        .HasForeignKey("StudyDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudieAssistenten.Shared.Models.Test", "Test")
                        .WithMany("GeneratedContents")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("StudyDocument");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("StudieAssistenten.Shared.Models.StudyDocument", b =>
                {
                    b.HasOne("StudieAssistenten.Shared.Models.Test", "Test")
                        .WithMany("Documents")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Test");
                });

            modelBuilder.Entity("StudieAssistenten.Shared.Models.GeneratedContent", b =>
                {
                    b.Navigation("Flashcards");
                });

            modelBuilder.Entity("StudieAssistenten.Shared.Models.StudyDocument", b =>
                {
                    b.Navigation("GeneratedContents");
                });

            modelBuilder.Entity("StudieAssistenten.Shared.Models.Test", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("GeneratedContents");
                });
#pragma warning restore 612, 618
        }
    }
}
